const ACTION_TYPES = {
    CREATE_HERO: 'CREATE_HERO',
    CREATE_HERO_REQUEST: 'CREATE_HERO_REQUEST',
    CREATE_HERO_SUCCESS: 'CREATE_HERO_SUCCESS',
    CREATE_HERO_ERROR: 'CREATE_HERO_ERROR',
    CREATE_IMAGE: 'CREATE_HERO',
    CREATE_IMAGE_REQUEST: 'CREATE_IMAGE_REQUEST',
    CREATE_IMAGE_SUCCESS: 'CREATE_IMAGE_SUCCESS',
    CREATE_IMAGE_ERROR: 'CREATE_IMAGE_ERROR',

    GET_HEROES: 'GET_HEROES',
    GET_HEROES_REQUEST: 'GET_HEROES_REQUEST',
    GET_HEROES_SUCCESS: 'GET_HEROES_SUCCESS',
    GET_HEROES_ERROR: 'GET_HEROES_ERROR',

    GET_HERO: 'GET_HERO',
    GET_HERO_REQUEST: 'GET_HERO_REQUEST',
    GET_HERO_SUCCESS: 'GET_HERO_SUCCESS',
    GET_HERO_ERROR: 'GET_HERO_ERROR'
}

export default ACTION_TYPES;